### PR TITLE
Add .npmrc file to disable package-lock.json

### PR DESCRIPTION
**Pull request by XhmikosR**
This is the recommended way IIRC

### CODE REVIEW

**Comment by nt1m** [comment]
I think it may be desirable to have it generated for local development, since there are benefits: https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json .

It's already in `.gitignore` so it won't be committed anyway. And if someone wants to disable it locally, they can put it in their global `.npmrc` file: https://docs.npmjs.com/cli/v6/configuring-npm/npmrc#global-config-file

In other words, I don't see a benefit of having `.npmrc` committed.

@XhmikosR What do you think? I'm open to merging this if you think it's a burden to have package-lock.json generated locally.

**Comment by XhmikosR** [comment]
It's an extra step because package-lock.json is enabled by default. So, if you want it disabled, that's how you do it in public repos..

**Comment by XhmikosR** [comment]
@evilpie can you take care of this trivial PR too please?

**Comment by nt1m** [comment]
I guess I don't mind too much, I still don't find it too useful though since someone who doesn't want it can just go one extra step and disable it glocally for their computer.

**Comment by XhmikosR** [comment]
This is about people who use the defaults. Someone who has disabled it globally isn't affected by this.

**Pull request merged**
