### PR TITLE
Support relative item URLs for RSS feeds

### PR DESCRIPTION
**Pull request by nt1m**

### CODE REVIEW

**Comment by nt1m** [comment]
@evilpie Do you have time to review this ?

This fixes #202 and #209 for RSS feeds only, not Atom feeds. I'm not sure what the standard is for Atom feeds, the page you've linked seems to mention `base`, but that wasn't used for RSS feeds which left me unsure.

**Comment by evilpie** [comment]
`new URL()` will throw when itemURL or websiteURL is not valid. I would do something like:
```
try {
   new URL(...)
} catch {
  itemURL
}
```

**Comment by evilpie** [comment]
https://magic.wizards.com/en/rss/rss.xml?tags=Daily%20MTG&lang=en uses `xml:base`

**Comment by evilpie** [comment]
@nt1m do you plan on updating this?

**Comment by nt1m** [comment]
@evilpie I unfortunately haven't had time lately, feel free to finish this off. I may only be able to get to it in a few weeks time.

**Comment by nt1m** [comment]
Thanks for reviewing btw, those are great points you brought up!

**Comment by evilpie** [comment]
I am looking into this. I think we can just ignore `xml:base` for now. `<link>` seems to be ok.

One weird thing about https://pastebin.com/raw/v99u0LiJ is:
```
	<atom:link href="/category/test/feed/" rel="self" type="application/rss+xml" />
	<link>https://pastebin.com</link>
```
and `doc.querySelector("link")` matches the `<atom:link>`, which makes no sense, because we are handling an RSS feed.

**Pull request closed without merging**
