### PR TITLE
Add button to remove broken livemark

### PR DESCRIPTION
**Pull request by fluoros-jp**
I thought it would be nice to have a functionality to simply remove a broken livemark after noticing some broken livemarks in my feed list.
So, I added a button to the "broken livemark dialog".

### CODE REVIEW

**Comment by nt1m** [comment]
Thanks for the PR! I'll review this ASAP and do any necessary adjustments :) It shouldn't take too much time but my health hasn't been too great this week.

**Comment by evilpie** [comment]
@fluoros-jp Thanks for the pull request. I made some adjustments https://github.com/nt1m/livemarks/commit/b406508d8ee434c162085fb7c056b3f08e5e1a6b to move the delete button next to select. I think that is similar to how to the normal edit dialog works.

**Comment by EverEve** [comment]
Thanks.
How long will it take before going live?

**Comment by evilpie** [comment]
When it's reviewed.

**Comment by fluoros-jp** [comment]
Thanks for merging!

**Pull request merged**
